Add Auth Rest API implementation
LucasBrazi06/ev-mobile pull request #258
Opened 2020-10-27 10:35 UTC by Ninjeneer

2020-10-27 10:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/LucasBrazi06/ev-mobile?pullRequest=258) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/LucasBrazi06/ev-mobile?pullRequest=258) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/LucasBrazi06/ev-mobile?pullRequest=258) it.</sub>

2020-10-27 11:19 UTC, jerome-benoit requested changes

2020-10-27 11:19 UTC, jerome-benoit commented on src/provider/CentralServerProvider.tsx
> +      `${this.buildRestServerAuthURL(tenant)}/${ServerAction.VERIFY_EMAIL}`, {
Same comment than the one done on the dashboard.

2020-10-27 11:19 UTC, jerome-benoit commented on src/provider/CentralServerProvider.tsx
> +    const result = await this.axiosInstance.get(`${this.buildRestServerAuthURL(tenant)}/${ServerAction.CHECK_END_USER_LICENSE_AGREEMENT}`, {
Same comment than the one done on the dashboard. 

Please test your changes ;)

2020-11-07 21:01 UTC, LucasBrazi06 requested changes

2020-11-07 21:01 UTC, LucasBrazi06 commented on src/provider/CentralServerProvider.tsx
> +      `${this.buildRestServerAuthURL(tenant)}/password/${ServerAction.REST_RESET}`,
Use REST_PASSWORD_REST with full path and not REST_RESET which means nothing when you read the code!

2020-11-07 21:01 UTC, LucasBrazi06 commented on src/provider/CentralServerProvider.tsx
> +      `${this.buildRestServerAuthURL(tenant)}/password/${ServerAction.REST_RESET}`,
Use full path

2020-11-07 21:01 UTC, LucasBrazi06 commented on src/provider/CentralServerProvider.tsx
> +      `${this.buildRestServerAuthURL(tenant)}/mail/${ServerAction.REST_CHECK}`, {
Use full path

2020-11-07 21:02 UTC, Ninjeneer commented on src/types/Server.tsx
> +  REST_CHECK = 'check',
This naming has been asked by Jérôme, cf : https://github.com/LucasBrazi06/ev-server/pull/1865

2020-11-16 16:45 UTC, jerome-benoit approved these changes

2020-11-16 16:47 UTC, jerome-benoit requested changes
+ Changes requested by Serge not made.
+ Conflicts to resolve.

2020-11-18 21:21 UTC, jerome-benoit approved these changes

2020-11-29 01:09 UTC, merged